# Generated by Django 4.2.1 on 2023-05-21 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spendings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total', models.FloatField(default=0)),
            ],
        ),
    ]
