# Generated by Django 4.2.1 on 2023-05-22 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spendings', '0002_dailyexpense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(),
        ),
    ]
